#!/bin/sh
#
# Pull down early Linux-kernel directories from kernel.org and
# create an awk array mapping release to release date.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# Copyright (C) Meta Platforms, Inc., 2025
#
# Authors: Paul E. McKenney <paulmck@kernel.org>

T="`mktemp -d ${TMPDIR-/tmp}/findkorgdates.sh.XXXXXX`"
trap 'rm -rf $T' 0

for i in \
	v1.0 \
	v1.1 \
	v1.2 \
	v1.3 \
	v2.0 \
	v2.1 \
	v2.2 \
	v2.3 \
	v2.4
do
	wget https://kernel.org/pub/linux/kernel/$i -O $T/$i.html
	grep "linux-.*\.tar\.gz" $T/$i.html |
		sed -e 's/^<a href="linux-//' -e 's/\.tar\.gz.*a>//' > $T/$i.txt
		awk -v dq='"' < $T/$i.txt '
		{
			print "v2d[" dq $1 dq "] = " dq $2 dq ";";
		}' > $T/$i.awk
done
echo "# Automatically generated by $0.  DO NOT EDIT." > version2date.awk
cat $T/*.awk | sort -t '"' -V >> version2date.awk
